docs: testnet breaking changes
FuelLabs/breaking-change-log pull request #7
Opened 2024-04-29 20:53 UTC by matt-user

I skipped some breaking changes in the ts-sdk and sway as they seemed to be internal breaking changes.  Please correct me if I forgot somethign.

2024-04-30 14:19 UTC, petertonysmith94 reviewed
Just some suggests - looks good though 🚀

2024-04-30 14:19 UTC, petertonysmith94 commented on breaking-changes-log.md
> +`TransactionRequest.addCoinOutput` and `TransactionRequest.addChangeOutput` now requires an `assetId`, it no longer defaults to the `baseAssetId`.
```suggestion
`TransactionRequest.addCoinOutput` and `TransactionRequest.addChangeOutput` now requires an `assetId`, it no longer defaults to the `BaseAssetId`.
```

2024-04-30 14:19 UTC, petertonysmith94 commented on breaking-changes-log.md
> +
May be worth having an example for this one?

```ts
/* BEFORE */
let coin = [1000];
coin = { amount: 1000 };

/* AFTER */
const assetId = "0x..";
let coin = [1000, assetId];
coin = { amount: 1000, assetId };
```

2024-04-30 14:19 UTC, petertonysmith94 commented on breaking-changes-log.md
> +async fund<T extends TransactionRequest>(request: T, params: EstimatedTxParams): Promise<T>
Is it worth being explicit with the `EstimatedTxParams` here? 

```suggestion
export type EstimatedTxParams = {
  minFee: BN;
  estimatedPredicates: TransactionRequestInput[];
  addedSignatures: number;
  requiredQuantities: CoinQuantity[];
}
async fund<T extends TransactionRequest>(request: T, params: EstimatedTxParams): Promise<T>
```

2024-05-02 11:34 UTC, danielbate commented on breaking-changes-log.md
> +
Hmm this was due to the `forc` upgrade rather than a design decision our side, should it reference the sway breaking change?

2024-05-07 16:30 UTC, xunilrj commented on breaking-changes-log.md
> +pub fn call_with_function_selectoir_vec(
small typo here.

2024-05-08 12:13 UTC, Torres-ssf requested changes

2024-05-08 12:13 UTC, Torres-ssf commented on breaking-changes-log.md
> +The `Account.fund` function parameters changed.
Can we add more info here saying that all properties present within the second parameter received by `Account.fund` are present within the response of `Provider.getTransactionCost` ?

2024-05-08 12:13 UTC, Torres-ssf commented on breaking-changes-log.md
> +  minFee: BN;
is `maxFee` here instead of `minFee`

2024-05-21 16:23 UTC, Br1ght0ne approved these changes
LGTM regarding Rust SDK sections, but I'd prefer more reviews from @FuelLabs/sdk-rust too.

2024-05-28 15:42 UTC, merged